- name: demo on conditions
  hosts: localhost
  connection: local
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg: hello world
      when: what == "world"

    - name: print hello universe
      ansible.builtin.debug:
        msg: hello universe
      when: what == "universe"
